apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm-2cpu
spec:
  disruption:
    consolidateAfter: 0s
    budgets:
      - nodes: 100%
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: Lt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]  # Compute, General Purpose, and Memory-optimized
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]