apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
  labels:
    app: pause
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "400m"
            memory: "512Mi"
          limits:
            memory: "1Gi"