apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
  labels:
    app: pause
spec:
  replicas: 20
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: pause
              topologyKey: kubernetes.io/hostname
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "350m"
            memory: "512Mi"
          limits:
            memory: "1Gi"